apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sl-pv1
spec:
  storageClassName: local-sentinel
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/sentinel/data1"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sl-pv2
spec:
  storageClassName: local-sentinel
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/sentinel/data2"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sl-pv3
spec:
  storageClassName: local-sentinel
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/sentinel/data3"
